<a href="https://colab.research.google.com/github/gk-anonymous/American-Express-Data-Analysis-Project/blob/main/AmericanExpresss.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install pandas

In [ ]:
pip install numpy

In [ ]:
pip install tensorflow

In [32]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [33]:
tf.__version__

'2.13.0'

In [34]:
dataset = pd.read_csv('American Express User Exit Prediction.csv')
x = dataset.iloc[:,0:-1].values
y = dataset.iloc[:,-1].values

In [35]:
print(x)

[[553.0 'Delhi' 'Female' ... 4.0 1.0 274150.0]
 [447.0 'Bengaluru' 'Male' ... 4.0 1.0 519360.0]
 [501.0 'Delhi' 'Female' ... 4.0 1.0 545501.0]
 ...
 [553.0 'Delhi' 'Male' ... 4.0 1.0 180031.0]
 [nan nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]]


In [36]:
#Gender column : Label Encoding

In [37]:
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()
x[:, 2] = label_encoder.fit_transform(x[:,2])

In [38]:
print(x)

[[553.0 'Delhi' 0 ... 4.0 1.0 274150.0]
 [447.0 'Bengaluru' 1 ... 4.0 1.0 519360.0]
 [501.0 'Delhi' 0 ... 4.0 1.0 545501.0]
 ...
 [553.0 'Delhi' 1 ... 4.0 1.0 180031.0]
 [nan nan 2 ... nan nan nan]
 [nan nan 2 ... nan nan nan]]


In [39]:
#Geography column : One hot Encoding

In [40]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])],remainder = 'passthrough')
x = np.array(ct.fit_transform(x))

In [41]:
print(x)

[[0.0 1.0 0.0 ... 4.0 1.0 274150.0]
 [1.0 0.0 0.0 ... 4.0 1.0 519360.0]
 [0.0 1.0 0.0 ... 4.0 1.0 545501.0]
 ...
 [0.0 1.0 0.0 ... 4.0 1.0 180031.0]
 [0.0 0.0 0.0 ... nan nan nan]
 [0.0 0.0 0.0 ... nan nan nan]]


In [42]:
#Splitting dataset into training

In [43]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2, random_state = 0)

In [44]:
#Future Scaling

In [45]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [46]:
#ANN Initilization

In [47]:
ann = tf.keras.models.Sequential()

In [48]:
#Adding Input layer and first hidden layer

In [50]:
#Adding second hidden layer

In [52]:
#Adding output layer

In [54]:
#ANN  compile

In [56]:
#Traning On training dataset

# New Section

In [65]:
import numpy as np
import pandas as pd
import tensorflow as tf
from sklearn.preprocessing import LabelEncoder, OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.model_selection import train_test_split

# Load the dataset
dataset = pd.read_csv('American Express User Exit Prediction.csv')

# Separate features (x) and target (y)
x = dataset.iloc[:, 0:-1].values
y = dataset.iloc[:, -1].values

# Encode categorical data
label_encoder = LabelEncoder()
x[:, 2] = label_encoder.fit_transform(x[:, 2])

# One-hot encode categorical data
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

# Split the dataset into training and testing sets
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=0)

# Standardize features
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

# Build the neural network model
ann = tf.keras.models.Sequential()
ann.add(tf.keras.layers.Dense(units=5, activation='relu'))
ann.add(tf.keras.layers.Dense(units=5, activation='relu'))
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

# Compile the model
ann.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# Train the model
ann.fit(x_train, y_train, batch_size=32, epochs=120)



Epoch 1/120
249/249 [==============================] - 1s 1ms/step - loss: nan - accuracy: 0.7176
Epoch 2/120
249/249 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.7937
Epoch 3/120
249/249 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.7937
Epoch 4/120
249/249 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.7937
Epoch 5/120
249/249 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.7937
Epoch 6/120
249/249 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.7937
Epoch 7/120
249/249 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.7937
Epoch 8/120
249/249 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.7937
Epoch 9/120
249/249 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.7937
Epoch 10/120
249/249 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.7937
Epoch 11/120
249/24

In [67]:
prediction = ann.predict(sc.transform([[0.0, 1.0,0, 0.0, 501, 0, 32, 2, 0.0, 4, 1, 545501]])) > 0.5
print(prediction)


1/1 [==============================] - 0s 233ms/step
[[False]]


In [68]:
y_pred = ann.predict(x_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((  y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

63/63 [==============================] - 0s 957us/step
[[0. 0.]
 [0. 1.]
 [0. 1.]
 ...
 [0. 1.]
 [0. 0.]
 [0. 0.]]


In [69]:
import numpy as np
from sklearn.metrics import confusion_matrix, accuracy_score

# Check for NaN values in y_test
nan_indices = np.isnan(y_test)

# Remove rows with NaN values from both y_test and corresponding rows in x_test
y_test = y_test[~nan_indices]
x_test = x_test[~nan_indices]

# Make predictions using your neural network model
y_pred = ann.predict(x_test) > 0.5

# Calculate confusion matrix and accuracy score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)


63/63 [==============================] - 0s 1ms/step
[[1595    0]
 [ 390    0]]
Accuracy: 0.8035264483627204


In [71]:
import numpy as np
import pandas as pd
import tensorflow as tf
from sklearn.preprocessing import LabelEncoder, OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score

# Load the dataset
dataset = pd.read_csv('American Express User Exit Prediction.csv')

# Separate features (x) and target (y)
x = dataset.iloc[:, 0:-1].values
y = dataset.iloc[:, -1].values

# Encode categorical data
label_encoder = LabelEncoder()
x[:, 2] = label_encoder.fit_transform(x[:, 2])

# One-hot encode categorical data
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

# Split the dataset into training and testing sets
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=0)

# Standardize features
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

# Build the neural network model
ann = tf.keras.models.Sequential()
ann.add(tf.keras.layers.Dense(units=5, activation='relu'))
ann.add(tf.keras.layers.Dense(units=5, activation='relu'))
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

# Compile the model
ann.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# Train the model
ann.fit(x_train, y_train, batch_size=32, epochs=120)

# Identify and remove rows with NaN values in y_test
nan_indices = np.isnan(y_test)
y_test_cleaned = y_test[~nan_indices]
x_test_cleaned = x_test[~nan_indices]

# Make predictions using your neural network model
y_pred = ann.predict(x_test_cleaned) > 0.5

# Calculate confusion matrix and accuracy score
cm = confusion_matrix(y_test_cleaned, y_pred)
accuracy = accuracy_score(y_test_cleaned, y_pred)

print("Confusion Matrix:")
print(cm)
print("Accuracy:", accuracy)


Epoch 1/120
249/249 [==============================] - 2s 2ms/step - loss: nan - accuracy: 0.5708
Epoch 2/120
249/249 [==============================] - 1s 3ms/step - loss: nan - accuracy: 0.7937
Epoch 3/120
249/249 [==============================] - 1s 4ms/step - loss: nan - accuracy: 0.7937
Epoch 4/120
249/249 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.7937
Epoch 5/120
249/249 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.7937
Epoch 6/120
249/249 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.7937
Epoch 7/120
249/249 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.7937
Epoch 8/120
249/249 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.7937
Epoch 9/120
249/249 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.7937
Epoch 10/120
249/249 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.7937
Epoch 11/120
249/24